; Mach 5 CSP Extension Config
; Authored by ohyeah2389

[BASIC]
RACING_CAR = 1
OPEN_WHEELER = 0
BRAKES_THRESHOLD = 0.01        ; How much brake pedal should be pressed for brake lights to turn on
IS_LOW_BEAM_AVAILABLE = 1      ; Are low beams available (by default available on street cars only)
SPARKS_UPWARDS_FORCE = 200

;MARK: Controls

[EXTRA_SWITCHES]
SWITCH_A = Control A: Jump Jacks
SWITCH_A_FLAGS = HOLD_MODE
SWITCH_E = Control E: Evening Eye

;MARK: Data Overrides

[DATA]
DISABLE_ANALOGINSTRUMENTSINI = 0
DISABLE_LIGHTSINI = 1
LIGHT_ANIMATION_TIME = 1 ; Alter duration of headlights animation

;MARK: Wobbly Tachometer

[INSTRUMENTS]
RPM_VINTAGE = 1 ; set to 1 to enable the whole thing
RPM_VINTAGE_ROUND_TO = 10 ; to what RPMs needle should snap
RPM_VINTAGE_DELAY = 0 ; delay between updates
RPM_VINTAGE_SPEED_LAG = 0.925 ; inertia value, from 0 to 1 (needle won’t move with 1)

;MARK: TyresFX

[WHEEL_LF, WHEEL_RF, WHEEL_LR, WHEEL_RR]
IS_OPEN = 0
TYRE_WIDTH = 0.17
TYRE_OFFSET = 0.0
RIM_WIDTH = 0.165
RIM_OFFSET = 0.0
;DEBUG = 1

[TYRES_FX]
ENABLED = 1
NOFX_DISTANCE_SWITCH = 20
VISIBLE_IN_INTERIOR_CAM = 0

WEAR_MAX_VIRTUAL_VM = 20
DAMAGE_FLAT_SPOT_GAIN = 1
DAMAGE_FLAT_SPOT_FADE = 0.1
DAMAGE_GRAIN_GAIN = 1
DAMAGE_GRAIN_MAX = 0.8
DAMAGE_WIDTH_K = 1.35
DAMAGE_OFFSET_K = 0
;DAMAGE_FLAT_SPOT_DEBUG = 1
;DAMAGE_GRAIN_DEBUG = 1

DAMAGE_SPEC_MULT = 1.4
DAMAGE_SPEC_EXP_MULT = 1
DAMAGE_REFL_MULT = 0.5
DAMAGE_OCCLUSION_MULT = 0.8
DAMAGE_NORMALS_MULT = 1.15

DIRT_ACCUMULATION = 60
DIRT_FADE = 20
DIRT_OFFSET_K = 0.0
DIRT_WIDTH_K = 1.1
;DIRT_GRASS_DEBUG = 1
;DIRT_DIRT_DEBUG = 1

FLEX_MULT = 1.0
FLEX_PROFILE_MULT = 1.0
FLEX_SQUASH_SMOOTHING = 0.5 ; decrease for smoother changes
FLEX_SKEW_RANGE_MULT = 4
FLEX_SKEW_SMOOTHING = 0.1 ; decrease for smoother changes
FLEX_MAX_SKEW_MULT = 0.05

CUSTOM_NORMALS_POS = -0.09, 0.09
CUSTOM_NORMALS_SCALE = 20

BROKEN_TYRES_DYNAMIC = 1
BROKEN_TYRES_BASE_NUDGE = -0.1
BROKEN_TYRES_BASE_BRIGHTNESS = 2

;MARK: Headlights

[LIGHT_HEADLIGHT_1]
; certain values here are overridden in the graphics script for Control E functionality
POSITION=0.637, 0.414, 2.31
DIRECTION=0, 0, 1
MIRROR=0
COLOR=0
RANGE=200
RANGE_GRADIENT_OFFSET=0.0
SPOT=60
SPOT_SHARPNESS=0.2
LOWBEAM_RANGE_MAX=120
LOWBEAM_RANGE_ONCOMING_MULT=2
SECOND_SPOT=160
SECOND_SPOT_INTENSITY=0.2
SECOND_SPOT_RANGE=30
SECOND_SPOT_SHARPNESS=0.4
FADE_AT=800
FADE_SMOOTH=200

[LIGHT_HEADLIGHT_2]
; certain values here are overridden in the graphics script for Control E functionality
POSITION=-0.637, 0.414, 2.31
DIRECTION=0, 0, 1
MIRROR=0
COLOR=0
RANGE=200
RANGE_GRADIENT_OFFSET=0.0
SPOT=60
SPOT_SHARPNESS=0.2
LOWBEAM_RANGE_MAX=120
LOWBEAM_RANGE_ONCOMING_MULT=2
SECOND_SPOT=160
SECOND_SPOT_INTENSITY=0.2
SECOND_SPOT_RANGE=30
SECOND_SPOT_SHARPNESS=0.4
FADE_AT=800
FADE_SMOOTH=200

;MARK: Scripts

[SCRIPT_...]
SCRIPT=graphics.lua